### ISSUE TITLE
Add Support for Python 3.12

### ISSUE THREAD

**Issue by patorf** [understand-ai/aveas_openlabel#11]
Hi, can you add support for python 3.12 ?

**Comment by monoclecat** [comment]
There is nothing speaking against this. Feel free to take the lead in contributing that to this repository. I can assist in the PR process.

**Comment by arossi07** [comment]
Hi can you assign me so that I can work on that?

**Comment by monoclecat** [comment]
Sure thing. Please add the 3.12 support to the Github Actions workflows as well. Otherwise we can't test code changes on 3.12 automatically before merging.
